# write a docker-compose.yml file with postgres

version: '3'
services:
  redis:
    image: redis
    hostname: redishost
    ports: 
      - 6379:6379
  ingestd:
    image: ingestd
    hostname: ingestd
    build: .
    ports: 
       - "8080:8080"
    volumes:
       - ./config.txt:/ingestd/config.txt
    depends_on:
       - redis
  redis_to_db:
    restart: on-failure
    image: redis_to_db
    hostname: r2db3
    environment: 
      redisClientAddr: "redishost"
      redisClientPort: "6379"
      redisClientPass: ""
      redisClientDB: 1
      redisSubscribeTopic: "example.table"
      targetDatabaseType: "postgres"
      targetDatabaseHost: "unused, change dsn."
      targetDatabasePort: 5432
      targetDatabaseObject: "example.table"
      targetDatabaseDatabase: "postgres"
      targetDatabaseDSN: "postgres://root@10.0.0.240:26257/example?sslmode=disable"
    depends_on:
       - redis

