# write a docker-compose.yml file with postgres

version: '3'
services:
  ingestd:
    image: ingestd
    hostname: ingestd
    build: .
    ports: 
        - "8080:8080"
    volumes:
        - ./config.txt:/ingestd/config.txt
    # depends_on:
    #     - redis
  postgres:
    image: postgres
    hostname: postgreshost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ingestd
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
        - 5432:5432
    volumes:
        - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis
    hostname: redishost
    ports: 
      - 6379:6379
  redis_to_db:
    restart: on-failure
    image: redis_to_db
    hostname: r2db1
    environment: 
      redisClientAddr: "redishost"
      redisClientPort: "6379"
      redisClientPass: ""
      redisClientDB: 1
      redisSubscribeTopic: "example.table"
      targetDatabaseType: "postgres"
      targetDatabaseHost: "unused, change dsn."
      targetDatabasePort: 5432
      targetDatabaseObject: "example.table"
      targetDatabaseDatabase: "postgres"
      targetDatabaseDSN: "postgres://postgres:postgres@postgreshost/postgres?sslmode=disable"
  redis_to_example_table_2:
    restart: on-failure
    image: redis_to_db
    hostname: r2db1
    environment: 
      redisClientAddr: "redishost"
      redisClientPort: "6379"
      redisClientPass: ""
      redisClientDB: 1
      redisSubscribeTopic: "example.table"
      targetDatabaseType: "postgres"
      targetDatabaseHost: "unused, change dsn."
      targetDatabasePort: 5432
      targetDatabaseObject: "example.table2"
      targetDatabaseDatabase: "postgres"
      targetDatabaseDSN: "postgres://postgres:postgres@postgreshost/postgres?sslmode=disable"
  redis_to_server_mysql:
    restart: on-failure
    image: redis_to_db
    hostname: r2db2
    environment: 
      redisClientAddr: "redishost"
      redisClientPort: "6379"
      redisClientPass: ""
      redisClientDB: 1
      redisSubscribeTopic: "example.table"
      targetDatabaseType: "mysql"
      targetDatabaseObject: "example.table"
      targetDatabaseDatabase: "mysql"
      targetDatabaseDSN: "redis_to_db:redis_to_db@tcp(10.0.0.252)/example?"
  redis_to_example_table_3:
    restart: on-failure
    image: redis_to_db
    hostname: r2db3
    environment: 
      redisClientAddr: "redishost"
      redisClientPort: "6379"
      redisClientPass: ""
      redisClientDB: 1
      redisSubscribeTopic: "example.table"
      targetDatabaseType: "postgres"
      targetDatabaseHost: "unused, change dsn."
      targetDatabasePort: 5432
      targetDatabaseObject: "example.table"
      targetDatabaseDatabase: "postgres"
      targetDatabaseDSN: "postgres://root@10.0.0.240:26257/example?sslmode=disable"

